CREATE DATABASE SoftUni;

GO

USE SoftUni;

GO

CREATE TABLE Towns
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Addresses
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	AddressText VARCHAR(MAX) NOT NULL,
	TownId INT,
	FOREIGN KEY (TownId) REFERENCES Towns(Id)
)

CREATE TABLE Departments
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(50) NOT NULL, 
	MiddleName VARCHAR(50) NULL, 
	LastName VARCHAR(50) NOT NULL, 
	JobTitle VARCHAR(MAX) NOT NULL, 
	DepartmentId INT,
	FOREIGN KEY (DepartmentId) REFERENCES Departments(Id),
	HireDate DATE NULL, 
	Salary DECIMAL(10,2) NULL, 
	AddressId INT,
	FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
)

