CREATE TABLE Students
(
	StudentID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Exams
(
	ExamID INT PRIMARY KEY IDENTITY(100,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE StudentsExams
(
	StudentID INT,
	FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
	ExamID INT,
	FOREIGN KEY (ExamID) REFERENCES Exams(ExamID),
	PRIMARY KEY(StudentID, ExamID),
)
