CREATE DATABASE [Online-Store-Database];

GO

USE [Online-Store-Database];

GO

CREATE TABLE Cities
(
	CityID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
	CustomerID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	BirthDay DATE NOT NULL,
	CityID INT,
	FOREIGN KEY (CityID) REFERENCES Cities(CityID)
)

CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	CustomerID INT,
	FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
)

CREATE TABLE Items
(
	ItemID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	ItemTypeID INT,
	FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems
(
	OrderID INT,
	FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
	ItemID INT,
	FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
	PRIMARY KEY (OrderID, ItemID)
)